// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXGmpDEeNKFaVVhpFoNncCbo3GqFUfpI',
    appId: '1:97893351344:web:b13e64122504a959712075',
    messagingSenderId: '97893351344',
    projectId: 'fir-notification-9fdbf',
    authDomain: 'fir-notification-9fdbf.firebaseapp.com',
    storageBucket: 'fir-notification-9fdbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEvisVJwS9THSXk8lNgbkgEIVlXdOq7c',
    appId: '1:97893351344:android:ff389d4713814e97712075',
    messagingSenderId: '97893351344',
    projectId: 'fir-notification-9fdbf',
    storageBucket: 'fir-notification-9fdbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzScs135G0dX-w3KGKWkUfjEXudDDVVUI',
    appId: '1:97893351344:ios:8f0568f5ac615ec3712075',
    messagingSenderId: '97893351344',
    projectId: 'fir-notification-9fdbf',
    storageBucket: 'fir-notification-9fdbf.appspot.com',
    iosBundleId: 'com.example.pushnotificationFunctionality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzScs135G0dX-w3KGKWkUfjEXudDDVVUI',
    appId: '1:97893351344:ios:7cd3e7764eb8b6f7712075',
    messagingSenderId: '97893351344',
    projectId: 'fir-notification-9fdbf',
    storageBucket: 'fir-notification-9fdbf.appspot.com',
    iosBundleId: 'com.example.pushnotificationFunctionality.RunnerTests',
  );
}
